<!-- <script>
// var err = new Error('出错了');
// console.log(err.message);
// // console.log(err.name);
// // console.log(err.stack);

// if (err.name) {
//     console.log(err.name + ': ' + err.message);  
// }

function throwit() {
    throw new Error('');
}

function catchit() {
    try {
        throwit();
    } catch(e) {
        console.log(e.stack);
    }
}

catchit();
</script> -->

<!-- <script>
// var 1a;

// console.log 'hello');

// unknownVariable;

// console.log() = 1;

// this = 1;

// new Array(-1);

// new 123;

// var obj = {};
// // obj.unknownMethod();
// console.log(obj.unknownMethod);

// decodeURI('%2')

var err1 = new Error('出错了！');
var err2 = new RangeError('出错了，变量超出有效范围！');
var err3 = new TypeError('出错了，变量类型无效！');
console.log(err1.message);
console.log(err2.message);
console.log(err3.message);
</script> -->

<!-- <script>
function UserError(message) {
    this.message = message || '默认信息';
    this.name = 'UserError';
}

UserError.prototype = new Error();
UserError.prototype.constructor = UserError;

var e = new UserError('这是自定义的错误！');
console.log(e.message);
</script> -->

<!-- <script>
// var x = 0;

// if (x <= 0){
//     throw new Error('x 必须为正数');
// }

// function UserError(message) {
//     this.message = message || '默认信息';
//     this.name = 'UserError'
// }

// throw new UserError('出错了！');

// throw 'Error!';
// throw 42;
// throw true;
throw {
    toString: function () {
        return 'Error';
    }
};
</script> -->

<!-- <script>
// try {
//     throw new Error('出错了');
// } catch (e) {
//     console.log(e.name + ": " + e.message);
//     console.log(e.stack);
// }

// try {
//     f();
// } catch (e) {
//     console.log(e);
// }

// try {
//     throw '出错了';
// } catch (e) {
//     console.log(111);
// }
// console.log(222);

// var n = 100;

// try {
//     throw n;
// } catch (e) {
//     if (e <= 50) {

//     } else {
//         throw e;
//     }
// }


try {
    foo.bar();
} catch (e) {
    if (e instanceof EvalError) {
        console.log(e.name + ': ' + e.message);
    } else if (e instanceof RangeError) {
        console.log(e.name + ': ' + e.message);
    } else if (e instanceof ReferenceError) {
        console.log(e.name + ': ' + e.message);
    }
}
</script> -->

<script>
// function cleansUp() {
//     try {
//         throw new Error('出错了');
//         console.log('慈航不会执行');
//     } finally {
//         console.log('完成清理工作');
//     }
// }

// cleansUp();

// function idle(x) {
//     try {
//         console.log(x);
//         return 'result';
//     } finally {
//         console.log('finally');
//     }
// }

// console.log(idle('hello'));

// var count = 0;

// function countUp() {
//     try {
//         return count;
//     } finally {
//         count++;
//     }
// }

// console.log(countUp());
// console.log(count);

// openFile();

// try {
//     writeFile(Data);
// } catch (e) {
//     handleError(e);
// } finally {
//     closeFile();
// }

// function f() {
//     try {
//         console.log(0);
//         throw 'bug';
//     } catch (e) {
//         console.log(1);
//         return true;
//         console.log(2);
//     } finally {
//         console.log(3);
//         return false;
//         console.log(3);
//     }

//     console.log(5);
// }

// var result = f();
// console.log(result);

function f() {
    try {
        throw '出错率';
    } catch (e) {
        console.log('捕捉到内部错误');
        throw e;
    } finally {
        return false;
    }
}

try {
    f();
} catch (e) {
    console.log('caught outer "bogus"');
}
</script>